In [ ]:
#LAB2_ASDS5303
#UTA ID -1002186838
#Name:Jeyasooriya Saravanan

import numpy as np
from scipy.linalg import null_space
import sympy as py

In [3]:
# Q1: use sample function to generate a random 10x10 matrix A with integers in [-10, 10] and compute the determinant of A.

In [34]:
A = np.random.randint(-10, 11, size=(10, 10))
A


array([[-10,  -6,  -5,  -4,  -2,  10,   7,   5,  -6,  -1],
       [  0,  -9,  -9,  -3,  -1,  -7,  -4,   1,   4,   8],
       [-10,   4,  -7,   2,   0,  10,   1,  -6,  -4,  -6],
       [  5,  10,  -7,   2,  -6,  10,  -2,   4,   5,  10],
       [ -7,   5,   3,   6,   7,  -5,  -1,  -7, -10,  -5],
       [-10,   7,   8,  -6,  -8,   6,  -7,  -8,   0,   3],
       [  6,  -3,  -1, -10,   0,   8,   1,  -8,  -8,  -7],
       [ -7,   8,   4,  -7,  10,   7,   8,   4,  -1,  -9],
       [ -6,   0,   1,  -2,   1,  -8,   9,   6, -10, -10],
       [ -4,   9,   4,   0,   9,  -2,   3,  -8,  -7,  -8]])

In [5]:
# Q2: Verify whether A is invertible.

In [35]:
determinant_A = np.linalg.det(A)
if(determinant_A !=0):
    print("The matrix A is invertible")
else:
    print("The matrix A is not invertible")


The matrix A is invertible


In [36]:
# Q3: 
# 1). If your A is NOT invertible., then regenerate A for this question. Otherwise, continue to 2).

# 2). Verify the determinant of inverse of A equals to 1 over the determinant of A


if(determinant_A ==0):
    while (determinant_A ==0):
        A = np.random.randint(-10, 11, size=(10, 10))
        print("The Matrix A is :")
        print(A)
else:
    print("The Matrix A is invertible. ")
    Inverse_A = np.linalg.inv(A)
    if((round(np.linalg.det(Inverse_A),4))==(round((1/determinant_A),4))):
        print("TRUE, The determinant of inverse of A equals to 1 over the determinant of A")
    else:
        print("FALSE, The determinant of inverse of A not equals to 1 over the determinant of A")


The Matrix A is invertible. 
TRUE, The determinant of inverse of A equals to 1 over the determinant of A


In [37]:
# Q4: 
# 1). Compute the null space of A.
null_space_A = null_space(A)
print(null_space_A)
# 2). How many solutions do you expect Ax=b have and why? b can be any 10 dimensional real vectors.

b = np.random.rand(10)
x, residual, Rank, Singular_values= np.linalg.lstsq(A, b, rcond=None)
print(x)
print("Rank of matrix B:", Rank)
if Rank == 10:
    print(np.linalg.solve(A,b))
    print("Unique Solution")
elif Rank < 10:
    M1=py.Matrix(np.append(A,b.reshape(10,1),axis=1))
    print(M1.rref())
    print("Infinite Solutions (Underdetermined)")
else:
    print("No Solution (Inconsistent)")

[]
[-0.01939376  0.06479013 -0.06967193 -0.08216761  0.04243874 -0.01421471
 -0.06905007  0.0067259  -0.0833368   0.01702573]
Rank of matrix B: 10
[-0.01939376  0.06479013 -0.06967193 -0.08216761  0.04243874 -0.01421471
 -0.06905007  0.0067259  -0.0833368   0.01702573]
Unique Solution


In [13]:
# Q5: 
# 1). Generate a random 3 x 5  matrix B with integers in [-10, 10] and a solution vector b with real numbers in [-5, 5].
# 2). Obtain the vector space including all the solutions of the system of equations Bx=b. 

In [38]:
np.random.seed(0) 

B = np.random.randint(-10, 11, size=(3, 5))
b1 = np.random.uniform(-5, 5, size=(3))

x, residuals, rank, singular_values = np.linalg.lstsq(B, b1, rcond=None)

null_space_B = null_space(B,b1)
print(null_space_B)
print("Matrix B:")
print(B)
print("\nVector b1:")
print(b1)
print("\nSolution Vector is :")
print(x)

print("Rank of matrix B:", rank)
if rank == 5:
    np.linalg.solve(B,b1)
    print("Unique Solution")
elif rank < 5:
    M=py.Matrix(np.append(B,b1.reshape(3,1),axis=1))
    print(M.rref())
    print("Infinite Solutions (Underdetermined)")
else:
    print("No Solution (Inconsistent)")

Matrix B:
[[  2   5 -10  -7  -7]
 [ -3  -1   9   8  -6]
 [ -4   2  -9  -4  -3]]

Vector b1:
[0.2889492  0.68044561 4.25596638]

Solution Vector is :
[-0.62169148 -0.09072205 -0.25637308  0.10908957 -0.02654837]
Rank of matrix B: 3
(Matrix([
[1, 0, 0, -0.527896995708155,  0.824034334763948,  -0.70115631286761],
[0, 1, 0,  0.304721030042918,  -3.23175965665236, 0.0283178037926663],
[0, 0, 1,  0.746781115879828, -0.751072961373391, -0.154967280430093]]), (0, 1, 2))
Infinite Solutions (Underdetermined)
